userRole: asd
server.port: 5697
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: buhhu8
    password: 0280829
    hikari:
      maximum-pool-size: 5
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.query.plan_cache_max_size: 32
      hibernate.query.plan_parameter_metadata_max_size: 128
      hibernate.criteria.literal_handling_mode: bind
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
  liquibase:
    enabled: true
    default-schema: buhhu8
    user: buhhu8
    password: 0280829
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    change-log: classpath:db/liquibase/changelog_master.xml
    contexts: test