spring:
  application:
    name: config-client
  profiles:
    active: vault
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.0.1
          scheme: http
          authentication: TOKEN
          token: 00000000-0000-0000-0000-000000000000
          kv-version: 2
server:
  port: 8888